<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <!-- Single File Publish Settings -->
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DefaultItemExcludes>$(DefaultItemExcludes);ChromeProfileLauncher.Tests\**;scratch\**</DefaultItemExcludes>
  </PropertyGroup>


  <ItemGroup>
    <Compile Remove="ChromeProfileLauncher.Tests\**" />
    <EmbeddedResource Remove="ChromeProfileLauncher.Tests\**" />
    <None Remove="ChromeProfileLauncher.Tests\**" />
    <Page Remove="ChromeProfileLauncher.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.5" />
    <PackageReference Include="Velopack" Version="0.0.1054" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

</Project>
